apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-app
  template:
    metadata:
      labels:
        app: server-app
    spec:
      containers:
      - name: app-deploy
        image: model-server:default
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "200m"
        envFrom:
        - configMapRef:
            name: model-config
        volumeMounts:
        - name: deploy-mount
          mountPath: /app/model
        ports:
        - containerPort: 5000
      volumes:
      - name: deploy-mount
        hostPath:
          path: /tmp
          type: Directory
